version: '3'

services:

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "9999:80"
    volumes:
      - .:/app/

    networks:
      - altcointrader-backtest-system_altcoin-net

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
    networks:
      - altcointrader-backtest-system_altcoin-net


networks:
  altcointrader-backtest-system_altcoin-net:
    external: true
